baseURL = "https://www.cedarbaum.io"
languageCode = "en-us"
title = "Hi, I am Sam."
theme = "hugo-theme-basic"
copyright = "Built with <a href='https://gohugo.io/' class='link black-40'>Hugo</a> and <a href='https://ox-hugo.scripter.co/' class='link black-40'>ox-hugo</a>. This website does not use :cookie:s."

enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "emacs"

[params]
# titleEmoji = ":pizza: :running:"
  twitter = "_cedarbaum"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[Permalinks]
  post = "post/:slug"

# [[params.menu]]
  # name = "blog"
  # url = "post/"

[[params.menu]]
  name = "about"
  url = "about/"